name: Auto Commit

on:
  schedule:
    - cron: "* * * * *"   # каждую минуту
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Make commits
        run: |
          for i in 1 2; do
            date >> heartbeat.txt
            git add heartbeat.txt
            git commit -m "Auto commit $i at $(date)"
            sleep 30
          done

      - name: Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"
          git push origin "HEAD:${BRANCH}"
