name: Burst 100 PRs (robust)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: burst-prs
  cancel-in-progress: false

jobs:
  make-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tools
        run: |
          set -e
          if ! command -v jq >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi
          command -v curl >/dev/null

      - name: Detect base branch
        id: base
        run: |
          # 1) из контекста события
          BASE="${{ github.event.repository.default_branch }}"
          # 2) если пусто, читаем символическую ссылку origin/HEAD
          if [ -z "$BASE" ]; then
            BASE=$(git symbolic-ref --short refs/remotes/origin/HEAD | sed -e 's|^origin/||')
          fi
          # 3) если всё ещё пусто — пробуем main/master
          if [ -z "$BASE" ]; then
            if git show-ref --verify --quiet refs/remotes/origin/main; then BASE=main; fi
            if [ -z "$BASE" ] && git show-ref --verify --quiet refs/remotes/origin/master; then BASE=master; fi
          fi
          echo "base=$BASE" >> $GITHUB_OUTPUT
          echo "Using base branch: $BASE"
          # убедимся, что локальная копия базы есть
          git fetch origin "$BASE":"refs/remotes/origin/$BASE"

      - name: Setup Git author
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Create 100 PRs ~6s apart
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO:  ${{ github.repository }}
          BASE:  ${{ steps.base.outputs.base }}
        run: |
          set -e
          mkdir -p pr_logs
          COUNT=100
          INTERVAL=6   # ~10 минут суммарно
          # уникальный префикс, чтобы точно не пересекаться
          PREF="auto/pr-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          for i in $(seq 1 "$COUNT"); do
            BR="${PREF}-$i"

            # создаём ветку от актуальной базы
            git checkout -B "$BR" "origin/$BASE"

            # реальное изменение: уникальная строка
            echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC') run=${GITHUB_RUN_ID} i=$i" >> "pr_logs/entry-$i.txt"
            git add pr_logs/entry-$i.txt
            # не даём фейлиться, если вдруг нет diffs (но такого тут не будет)
            git commit -m "chore: add pr_logs/entry-$i.txt" || echo "No changes to commit for $BR"

            # пуш ветки (ошибки пуша считаем критичными)
            git push -u origin "$BR"

            # создаём PR
            BODY=$(jq -n \
              --arg title "Auto PR #$i (run ${GITHUB_RUN_ID})" \
              --arg head "$BR" \
              --arg base "$BASE" \
              --arg desc "Automated PR $i from $BR to $BASE" \
              '{title:$title, head:$head, base:$base, body:$desc, draft:false}')
            RESP=$(curl -sS -X POST \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$BODY" "https://api.github.com/repos/$REPO/pulls")

            NUM=$(echo "$RESP" | jq -r '.number // empty')
            ERR=$(echo "$RESP" | jq -r '.errors[]?.message // empty')
            MSG=$(echo "$RESP" | jq -r '.message // empty')

            if [ -n "$NUM" ]; then
              echo "Opened PR #$NUM from $BR -> $BASE"
            else
              echo "PR creation warning for $BR: ${ERR:-$MSG}"
              # не падаем из-за единичной ошибки, идём дальше
            fi

            sleep "$INTERVAL"
          done
